import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { createClient } from '@/utils/supabase/server'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function displayNavBar() {
  const supabase = createClient()

  const { data, error } = await supabase.auth.getUser()

  if (error || !data?.user) {
    return false
  }
  return true
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {await displayNavBar() ? <Navbar /> : null}
        <section className="bg-gray-300 h-screen">
          {children}
        </section>
      </body>
    </html>
  );
}
